xinit fixes

diff --git a/x11/misc/xinit/files/Xsession b/x11/misc/xinit/files/Xsession
--- a/x11/misc/xinit/files/Xsession
+++ b/x11/misc/xinit/files/Xsession
@@ -1,56 +1,122 @@
 #!/bin/sh
 #
-# X session wrapper
+# /etc/X11/Xsession
+#
+# global Xsession file -- used by display managers and xinit (startx)
 
-echo "Running X session wrapper"
+# $Id: Xsession 967 2005-12-27 07:20:55Z dnusinow $
+
+set -e
+
+PROGNAME=Xsession
+
+message () {
+  # pretty-print messages of arbitrary length; use xmessage if it
+  # is available and $DISPLAY is set
+  MESSAGE="$PROGNAME: $*"
+  echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} >&2
+  if [ -n "$DISPLAY" ] && which xmessage > /dev/null 2>&1; then
+    echo "$MESSAGE" | fold -s -w ${COLUMNS:-80} | xmessage -center -file -
+  fi
+}
+
+message_nonl () {
+  # pretty-print messages of arbitrary length (no trailing newline); use
+  # xmessage if it is available and $DISPLAY is set
+  MESSAGE="$PROGNAME: $*"
+  echo -n "$MESSAGE" | fold -s -w ${COLUMNS:-80} >&2;
+  if [ -n "$DISPLAY" ] && which xmessage > /dev/null 2>&1; then
+    echo -n "$MESSAGE" | fold -s -w ${COLUMNS:-80} | xmessage -center -file -
+  fi
+}
+
+errormsg () {
+  # exit script with error
+  message "$*"
+  exit 1
+}
+
+internal_errormsg () {
+  # exit script with error; essentially a "THIS SHOULD NEVER HAPPEN" message
+  # One big call to message() for the sake of xmessage; if we had two then
+  # the user would have dismissed the error we want reported before seeing the
+  # request to report it.
+  errormsg "$*" \
+           "Please report the installed version of the \"x11-common\"" \
+           "package and the complete text of this error message to" \
+           "<debian-x@lists.debian.org>."
+}
+
+# initialize variables for use by all session scripts
+
+OPTIONFILE=/etc/X11/Xsession.options
+
+SYSRESOURCES=/etc/X11/Xresources
+USRRESOURCES=$HOME/.Xresources
+
+SYSSESSIONDIR=/etc/X11/Xsession.d
+USERXSESSION=$HOME/.xsession
+USERXSESSIONRC=$HOME/.xsessionrc
+ALTUSERXSESSION=$HOME/.Xsession
+ERRFILE=$HOME/.xsession-errors
+
+# attempt to create an error file; abort if we cannot
+if (umask 077 && touch "$ERRFILE") 2> /dev/null && [ -w "$ERRFILE" ] &&
+  [ ! -L "$ERRFILE" ]; then
+  chmod 600 "$ERRFILE"
+elif ERRFILE=$(tempfile 2> /dev/null); then
+  if ! ln -sf "$ERRFILE" "${TMPDIR:=/tmp}/xsession-$USER"; then
+    message "warning: unable to symlink \"$TMPDIR/xsession-$USER\" to" \
+             "\"$ERRFILE\"; look for session log/errors in" \
+             "\"$TMPDIR/xsession-$USER\"."
+  fi
+else
+  errormsg "unable to create X session log/error file; aborting."
+fi
+
+exec >>"$ERRFILE" 2>&1
+
+echo "$PROGNAME: X session started for $LOGNAME at $(date)"
 
 # Load profile
-for file in /etc/profile "$HOME/.profile" /etc/xprofile "$HOME/.xprofile"; do
-	if [ -f "$file" ]; then
-		echo "Loading profile from $file";
-		. "$file"
-	fi
+set +e
+for file in "/etc/profile" "$HOME/.profile"; do
+  if [ -f "$file" ] && ! . "$file"; then
+    echo "Error loading $file"
+  fi
 done
+set -e
 
-# Load resources
-for file in /etc/X11/Xresources "$HOME/.Xresources"; do
-	if [ -f "$file" ]; then
-		echo "Loading resource: $file"
-		xrdb -nocpp -merge "$file"
-	fi
-done
-
-# Load keymaps
-use_xkbmap=false
-for file in "/etc/X11/Xkbmap" "$HOME/.Xkbmap"; do
-	if [ -f "$file" ]; then
-		echo "Loading keymap: $file"
-		setxkbmap `cat "$file"` && use_xkbmap=true
-	fi
-done
-
-# Load xmodmap if not using XKB
-if ! $use_xkbmap; then
-	for file in "/etc/X11/Xmodmap" "$HOME/.Xmodmap"; do
-		if [ -f "$file" ]; then
-		   echo "Loading modmap: $file"
-		   xmodmap "$file"
-		fi
-	done
+# sanity check; is our session script directory present?
+if [ ! -d "$SYSSESSIONDIR" ]; then
+  errormsg "no \"$SYSSESSIONDIR\" directory found; aborting."
 fi
 
-# Run all system xinitrc shell scripts.
-xinitdir="/etc/X11/xinit/xinitrc.d"
-if [ -d "$xinitdir" ]; then
-	for script in $xinitdir/*; do
-		echo "Loading xinit script $script"
-		if [ -x "$script" -a ! -d "$script" ]; then
-			. "$script"
-		fi
-	done
+# Attempt to create a file of non-zero length in /tmp; a full filesystem can
+# cause mysterious X session failures.  We do not use touch, :, or test -w
+# because they won't actually create a file with contents.  We also let standard
+# error from tempfile and echo go to the error file to aid the user in
+# determining what went wrong.
+WRITE_TEST=$(tempfile)
+if ! echo "*" >>"$WRITE_TEST"; then
+  message "warning: unable to write to ${WRITE_TEST%/*}; X session may exit" \
+          "with an error"
+fi
+rm -f "$WRITE_TEST"
+
+# use run-parts to source every file in the session directory; we source
+# instead of executing so that the variables and functions defined above
+# are available to the scripts, and so that they can pass variables to each
+# other
+SESSIONFILES=$(run-parts --list $SYSSESSIONDIR)
+if [ -n "$SESSIONFILES" ]; then
+  set +e
+  for SESSIONFILE in $SESSIONFILES; do
+    . $SESSIONFILE
+  done
+  set -e
 fi
 
-echo "X session wrapper complete, running session $@"
+exit 0
 
-exec $@
-
+# vim:set ai et sts=2 sw=2 tw=80:
